# Generates FRENCH_REVIEW.md from the shipped DefInjected French/English XML, so the review columns
# cannot drift from the mod (TRANSLATIONS.md section 3, "Systematic French review by Virginie").
# No Keyed folder in this mod: only DefInjected. English source text is read from Mod/Defs (the def's
# own field), the same source the game falls back to when a DefInjected entry is missing.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$frenchRoot = Join-Path $root 'Mod\Languages\French\DefInjected'
$defsRoot = Join-Path $root 'Mod\Defs'
$rev = (git -C $root rev-parse --short HEAD).Trim()

# Loads every Def XML once, indexed by (DefType, defName) -> XmlElement, so field lookups below don't
# reparse the tree per key.
function Get-AllDefs {
    $defs = @{}
    $files = Get-ChildItem -Path $defsRoot -Filter '*.xml' -Recurse
    foreach ($f in $files) {
        [xml]$doc = Get-Content $f.FullName -Raw
        foreach ($node in $doc.DocumentElement.ChildNodes) {
            if ($node.NodeType -ne 'Element') { continue }
            $dn = $node.SelectSingleNode('defName')
            if ($null -eq $dn) { continue }
            $defs["$($node.Name)|$($dn.InnerText.Trim())"] = $node
        }
    }
    return $defs
}
$AllDefs = Get-AllDefs

# corePart.parts.NAME.(parts.NAME...).customLabel or .label: parts is an unkeyed <li> list, matched by
# walking it and testing each candidate <parts><li> for a nested <li> (any depth) whose own leaf field
# equals NAME once slugified (lowercase, spaces->underscores) — the same slug DefInjected keys use.
function Find-PartsNode {
    param($PartsListNode, [string]$Slug)
    if ($null -eq $PartsListNode) { return $null }
    foreach ($li in $PartsListNode.ChildNodes) {
        if ($li.NodeType -ne 'Element') { continue }
        $lbl = $li.SelectSingleNode('customLabel')
        if ($null -eq $lbl) { $lbl = $li.SelectSingleNode('label') }
        if ($null -eq $lbl) { $lbl = $li.SelectSingleNode('def') } # unnamed part, e.g. Neck, Head: match by defName
        if ($null -ne $lbl) {
            $candidate = ($lbl.InnerText.Trim().ToLowerInvariant() -replace '\s+', '_')
            if ($candidate -eq $Slug.ToLowerInvariant()) { return $li }
        }
    }
    return $null
}

function Get-DefFieldText {
    param([string]$DefType, [string]$DefName, [string]$FieldPath)
    $node = $AllDefs["$DefType|$DefName"]
    if ($null -eq $node) { return $null }
    $segs = $FieldPath -split '\.'
    $cur = $node
    $i = 0
    while ($i -lt $segs.Count) {
        $seg = $segs[$i]
        if ($seg -eq 'parts' -and $i + 1 -lt $segs.Count) {
            $partsList = $cur.SelectSingleNode('parts')
            if ($null -eq $partsList) { $partsList = $cur.SelectSingleNode('corePart/parts') }
            $slug = $segs[$i + 1]
            $cur = Find-PartsNode -PartsListNode $partsList -Slug $slug
            $i += 2
            continue
        }
        if (($seg -eq 'tools' -or $seg -eq 'lifeStages') -and $i + 1 -lt $segs.Count) {
            $list = $cur.SelectSingleNode($seg)
            $slug = $segs[$i + 1]
            $cur = Find-PartsNode -PartsListNode $list -Slug $slug
            $i += 2
            continue
        }
        if ($null -eq $cur) { return $null }
        $next = $cur.SelectSingleNode($seg)
        if ($null -eq $next) { $next = $cur.SelectSingleNode("corePart/$seg") }
        $cur = $next
        $i++
    }
    if ($null -ne $cur -and $cur.InnerText) { return $cur.InnerText.Trim() }
    return $null
}

$defTypeByFolder = @{ ThingDef = 'ThingDef'; BodyDef = 'BodyDef'; PawnKindDef = 'PawnKindDef' }

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review - Teshi")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``scripts/Generate-FrenchReview.ps1`` from revision ``$rev``. No source language other than")
[void]$out.AppendLine("English: the Original column repeats the English text (ATTRIBUTION.md, the mod has no non-English source).")
[void]$out.AppendLine("No Keyed strings in this mod, DefInjected only. None of these texts agree with a pawn (animal race labels")
[void]$out.AppendLine("and body-part names, not colonist-facing sentences), so the gender switch of TRANSLATIONS.md section 3 does")
[void]$out.AppendLine("not apply here.")
[void]$out.AppendLine()

$folders = Get-ChildItem -Path $frenchRoot -Directory | Sort-Object Name
foreach ($folder in $folders) {
    $defType = $defTypeByFolder[$folder.Name]
    if (-not $defType) { $defType = $folder.Name }
    $files = Get-ChildItem -Path $folder.FullName -Filter '*.xml' | Sort-Object Name
    foreach ($file in $files) {
        [void]$out.AppendLine("## $($folder.Name)/$($file.Name)")
        [void]$out.AppendLine()
        [void]$out.AppendLine("| Key or path | Original | English | French |")
        [void]$out.AppendLine("|---|---|---|---|")
        [xml]$fr = Get-Content $file.FullName -Raw
        $entries = $fr.LanguageData.ChildNodes | Where-Object { $_.NodeType -eq 'Element' }
        foreach ($entry in $entries) {
            $key = $entry.Name
            $frText = $entry.InnerText.Trim()
            # key shape: <DefName>.<field.path...>
            $dot = $key.IndexOf('.')
            $defName = $key.Substring(0, $dot)
            $fieldPath = $key.Substring($dot + 1)
            try {
                $en = Get-DefFieldText -DefType $defType -DefName $defName -FieldPath $fieldPath
            } catch {
                $en = $null
            }
            if ($null -eq $en) { $en = '_(not found in Defs — verify)_' }
            $enEsc = $en -replace '\|', '\|'
            $frEsc = $frText -replace '\|', '\|'
            [void]$out.AppendLine("| ``$key`` | $enEsc | $enEsc | $frEsc |")
        }
        [void]$out.AppendLine()
    }
}

$outPath = Join-Path $root 'FRENCH_REVIEW.md'
Set-Content -Path $outPath -Value $out.ToString() -Encoding utf8
Write-Host "Wrote $outPath"
